enum PaymentMethods {
    CARD = 'CARD',
    PSE = 'PSE',
    NEQUI = 'NEQUI',
    SU_PLUS = 'SU_PLUS',
    DAVIPLATA = 'DAVIPLATA',
    BANCOLOMBIA_TRANSFER = 'BANCOLOMBIA_TRANSFER',
    BANCOLOMBIA_QR = 'BANCOLOMBIA_QR',
    BANCOLOMBIA_COLLECT = 'BANCOLOMBIA_COLLECT',
    BANCOLOMBIA_BNPL = 'BANCOLOMBIA_BNPL',
}
export { PaymentMethods };